//
// PushNotification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PushNotification: Codable {

    public var _id: Int?
    public var uuid: String?
    public var title: String?
    public var message: String?
    public var badgeCount: Int?
    public var data: String?
    public var scheduledAt: String?
    public var scheduledTimezone: String?
    public var sentAt: String?
    public var readAt: String?
    public var notifiableType: String?
    public var notifiableId: String?
    public var topic: String?
    public var apnsConfig: String?
    public var androidConfig: String?
    public var deletedAt: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init(_id: Int?, uuid: String?, title: String?, message: String?, badgeCount: Int?, data: String?, scheduledAt: String?, scheduledTimezone: String?, sentAt: String?, readAt: String?, notifiableType: String?, notifiableId: String?, topic: String?, apnsConfig: String?, androidConfig: String?, deletedAt: String?, createdAt: String?, updatedAt: String?) {
        self._id = _id
        self.uuid = uuid
        self.title = title
        self.message = message
        self.badgeCount = badgeCount
        self.data = data
        self.scheduledAt = scheduledAt
        self.scheduledTimezone = scheduledTimezone
        self.sentAt = sentAt
        self.readAt = readAt
        self.notifiableType = notifiableType
        self.notifiableId = notifiableId
        self.topic = topic
        self.apnsConfig = apnsConfig
        self.androidConfig = androidConfig
        self.deletedAt = deletedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case uuid
        case title
        case message
        case badgeCount = "badge_count"
        case data
        case scheduledAt = "scheduled_at"
        case scheduledTimezone = "scheduled_timezone"
        case sentAt = "sent_at"
        case readAt = "read_at"
        case notifiableType = "notifiable_type"
        case notifiableId = "notifiable_id"
        case topic
        case apnsConfig = "apns_config"
        case androidConfig = "android_config"
        case deletedAt = "deleted_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }


}

