//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct User: Codable {

    public var _id: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var phone: String?
    public var avatarUrl: String?
    public var accessToken: String?

    public init(_id: String?, firstName: String?, lastName: String?, email: String?, phone: String?, avatarUrl: String?, accessToken: String?) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.avatarUrl = avatarUrl
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case phone
        case avatarUrl = "avatar_url"
        case accessToken = "access_token"
    }
}
